#!/bin/bash

HOSTNAME=$(hostname)
OS=$(lsb_release -d | awk -F'\t' '{print $2}')
UPTIME=$(uptime -p)
#hardware information
CPU=$(lshw -class processor | grep "product:" | awk -F'product: ' '{print $2}')
SPEED=$(lshw -class processor | grep "capacity:" | awk -F'capacity: ' '{print $2}')
RAM=$(free -h | grep "Mem:" | awk '{print $2}')
DISKS=$(lsblk -d -o NAME,MODEL,SIZE | grep -v NAME | awk '{print $2, $3}')
VIDEO=$(lshw -class display | grep "product:" | awk -F'product: ' '{print $2}')
#network information
FQDN=$(hostname -f)
IP=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS=$(cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}')
INTERFACE=$(ip link show | awk -F': ' '/^[0-9]+: [^lo]/ {print $2}' | head -n 1)
IPADDR=$(ip a show $INTERFACE | grep "inet " | awk '{print $2}')
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd, -)
DISK_SPACE=$(df -h | grep '^/dev' | awk '{print $6, $4}' | paste -sd,  -)
PROCESS_COUNT=$(ps aux --no-heading | wc -l)
LOAD_AVG=$(uptime | awk -F'load average: ' '{print $2}')
MEMORY_ALLOC=$(free -h)
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | paste -sd, -)
UFW_RULES=$(sudo ufw status numbered | grep "ALLOW" | awk '{$1=$2=""; print $0}' | paste -sd, -)

echo
echo "System Report generated by $(whoami), $(date)"
echo
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "Speed: $SPEED"
echo "RAM: $RAM"
echo "Disk(s): $DISKS"
echo "Video: $VIDEO"
echo
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo
echo "InterfaceName: $INTERFACE"
echo "IP Address: $IPADDR"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVG"
echo "Memory Allocation:"
echo "$MEMORY_ALLOC"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Rules: $UFW_RULES"
echo
