#!/bin/bash

HOSTNAME=$(hostname) # get the system hostname
OS=$(lsb_release -d | awk -F'\t' '{print $2}') #get the information of os  
UPTIME=$(uptime -p) #get the system's time
#hardware information
CPU=$(lshw -class processor | grep "product:" | awk -F'product: ' '{print $2}') #get the cpu informations
SPEED=$(lshw -class processor | grep "capacity:" | awk -F'capacity: ' '{print $2}') #get the speed of cpu
RAM=$(free -h | grep "Mem:" | awk '{print $2}') #get the size of RAM
DISKS=$(lsblk -d -o NAME,MODEL,SIZE | grep -v NAME | awk '{print $2, $3}') #gets the size ,model and name of the installed disks 
VIDEO=$(lshw -class display | grep "product:" | awk -F'product: ' '{print $2}') #get the video card info
#network information
FQDN=$(hostname -f) #get the  domain name
IP=$(hostname -I | awk '{print $1}') #get the ip address of hostname
GATEWAY=$(ip r | grep default | awk '{print $3}') #get the gateway ip address
DNS=$(cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}') #get the dns server ip
INTERFACE=$(ip link show | awk -F': ' '/^[0-9]+: [^lo]/ {print $2}' | head -n 1) #get the network interface name
IPADDR=$(ip a show $INTERFACE | grep "inet " | awk '{print $2}') # Get the IP address in CIDR format
# System Status
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd, -) # Get a list of users currently logged in
DISK_SPACE=$(df -h | grep '^/dev' | awk '{print $6, $4}' | paste -sd,  -) #get the free space for local filesystems
PROCESS_COUNT=$(ps aux --no-heading | wc -l) #get the number of running processes
LOAD_AVG=$(uptime | awk -F'load average: ' '{print $2}') #get the loadd average
MEMORY_ALLOC=$(free -h) #get memory allocation's details 
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | paste -sd, -) # Get a list of listening network ports
UFW_RULES=$(sudo ufw status numbered | grep "ALLOW" | awk '{$1=$2=""; print $0}' | paste -sd, -) #get the ufw rules

#echo data
echo
echo "System Report generated by $(whoami), $(date)"
echo
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "Speed: $SPEED"
echo "RAM: $RAM"
echo "Disk(s): $DISKS"
echo "Video: $VIDEO"
echo
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo
echo "InterfaceName: $INTERFACE"
echo "IP Address: $IPADDR"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVG"
echo "Memory Allocation:"
echo "$MEMORY_ALLOC"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Rules: $UFW_RULES"
echo
